version: '3.7'

services:

  expenses:
    build: .
    container_name: expenses
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis


  db:
    image: postgres:11.5
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 9090:9090
    volumes:
      - expenses_db:/var/lib/postgresql/data/


  redis:
    image: "redis:alpine"
    container_name: redis
    hostname: redis


  celeryworker:
    build: .
    container_name: celeryworker
    restart: always
    command: celery -A expenses worker -l INFO
    env_file:
      - .env
    depends_on:
      - expenses
      - redis


  celerybeat:
    build: .
    container_name: celerybeat
    restart: always
    command: celery -A expenses beat -l INFO
    env_file:
      - .env
    depends_on:
      - expenses
      - redis


volumes:
  expenses_db:
