# Generated by Django 3.1.6 on 2021-04-19 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_api', '0004_remove_expense_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='expenses_api.salary'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='expenses_api.category'),
        ),
    ]
