# Generated by Django 3.1.6 on 2021-04-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_api', '0005_auto_20210419_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='month',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
