# Generated by Django 3.1.6 on 2021-04-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_api', '0006_salary_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Name')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Price')),
                ('priority', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name="Wish's priority")),
            ],
            options={
                'verbose_name': 'Wish',
                'verbose_name_plural': 'Wishes',
            },
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'Salary', 'verbose_name_plural': 'Salary'},
        ),
    ]
