# Generated by Django 3.1.6 on 2021-05-05 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_api', '0008_auto_20210505_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Salary Date'),
        ),
    ]
