# Generated by Django 3.1.6 on 2021-05-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_api', '0010_auto_20210505_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='history',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='parent',
        ),
        migrations.AddField(
            model_name='salary',
            name='history',
            field=models.BooleanField(default=False, verbose_name='History'),
        ),
        migrations.AddField(
            model_name='salary',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='expenses_api.salary'),
        ),
    ]
