# Generated by Django 3.1.6 on 2021-05-05 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_api', '0011_auto_20210505_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created'),
        ),
    ]
